### ISSUE TITLE
Compatibility issue on Edge

### ISSUE THREAD

**Issue by shanhuiyang** [dericgw/react-tiny-fab#44]
Found following error on Edge

> SCRIPT1028: SCRIPT1028: Expected identifier, string or number
fab.esm.js (84,1)

![edgeerror](https://user-images.githubusercontent.com/50712413/70374392-893db700-192c-11ea-9a00-222bdbe1f6f3.PNG)

**Comment by dericgw** [comment]
That is the ESM build which needs to be compiled before use.

**Comment by shanhuiyang** [comment]
Not sure how could I resolve the problem. No issue for other browsers.
Could you please illustrate what is the issue exactly?

**Comment by dericgw** [comment]
Are you testing this after running 
```
npm run build
```
Or, is this output from running
```
npm run start
```

**Comment by shanhuiyang** [comment]
Yes, I am using Create React App, did not configure anything, just run with `npm run start`

**Comment by dericgw** [comment]
You probably need to adjust your "Browserlist" setting for your development environment in order to get it working correctly. It seems like right now, your code is not compiling correctly to work with Edge. Read this for more information: https://create-react-app.dev/docs/supported-browsers-features/#configuring-supported-browsers

Closing for now, but please let me know if you have any more questions.
