### ISSUE TITLE
Define which way the menu is opened

### ISSUE THREAD

**Issue by frab90** [dericgw/react-tiny-fab#51]
Hello,
I'd like to use a `react-tiny-fab` in every Card component in the dashboard I'm creating.
It would be amazing to be free to position the `react-tiny-fab` in a position relative to its parent component.
It would be amazing to be free to define which way it expands.

For the moment I have positioned it this way but it's not clean at all.
```
 <Fab
        icon={<Settings />}
        event="hover"
        key={uuid.v4()}
        alwaysShowTitle={false}
        position={({ zIndex: 0, ...position })}
      >
```

Where `position` is calculated 
```
const offsets = { top: -90, left: -90 } // this is the distance from the bottom-left corner of the Card
const position = { top: top + height + offsets.top, left: left + width + offsets.left } // this is evaluated in something like {top: 200, left:500 }
```

I also had to pass the `zIndex` parameter through the `position` prop because I haven't found a cleaner way to customize the component.

I haven't found any beautiful alternative around and this is the reason why I'd like to be able to customize a little bit more.

Thank you

**Comment by dericgw** [comment]
@frab90 What would you propose the API should look like in order to achieve what you want? 

One way you could do this is by using CSS (I could even allow props to be passed down in case you are using Styled Components, or some type of CSS-in-JS). If you want to use CSS to do what you want, here is how:

```css
/* This is the main container around the FAB */
.rtf {
  position: absolute;
}
```
Then, the position you pass in would be relative to the nearest `relative` container - in your case, the Card component.

**Comment by frab90** [comment]
Thank you  @dericgw  for the quick reply.

**About the expansion direction**
I figured out that passing `bottom` instead of `top` to the `position` prop is enough to make the action appear upward. It works but if you want to allow more customization a way to improve it would be to add an `expand` prop with one of those values: `up`, `down`, `left`, `right`. If any value is provided for the `expand` prop, the component should automatically figure out the way to expand like it does right now.

```
 <Fab
       // other props
       expand={'up'} // if expand is not defined, the component automatically figures out which way to expand
      >
```

**About relative positioning and/or other custom styling**
 I need to override the both the `.rtf`'s `position` and the 'zIndex' attributes to achieve the result I want. Maybe someone else would be interested in overriding some other attributes. Do you think adding a `style` prop to the `Fab` component could make the component too complicated to use?

Does passing any styling attribute to the `position` prop do what I'm suggesting to achieve by adding a `style` prop?
If yes you could:
1. just rename `position` to `style` or 
2. letting us pass one between `position` and `style` or both. If both are passed their value have to be merged before being applied to the component.

For example

```
 <Fab
       // other props
       style={ /* custom style to apply to the .rtf class */}
       position={top: 30, left:50}
      >
```

Does it make sense?

**Comment by dericgw** [comment]
@frab90 I like your idea of changing the `position` prop to `style` prop - that really makes more sense because that is what it is used for. I also like the suggestion of having another prop like `expand` to allow the consumer to define which way the menu will expand. If I can get some time, I will implement this. This would require a new major version since the API would change (I wouldn't want to have to merge `position` and `style` because I would possibly need to merge three objects together and precedence could then become confusing.

If you wanted to take on this work and create a PR, you are more than welcome. It seems like you have a really good grasp on what should happen.

**Comment by dericgw** [comment]
This will be fixed in v4 which is about to be released.
