### ISSUE TITLE
Way to have the Fab positioned relative / inside another component?

### ISSUE THREAD

**Issue by rberger** [dericgw/react-tiny-fab#52]
Seems that the position prop only sets it relative to the page/viewport. Is there a way to have it be relative to a component / container instead?

**Comment by dericgw** [comment]
Part of this is discussed in #51. I believe I am going to spread props to the FAB container which would allow styles to be passed. You could use CSS to override the `.rtf` and set the position to `absolute` instead of `fixed` but I know this isn't very convenient for things like Styles Components. I'll try and get something out this week unless you want to create a PR. It should be a two line change by adding `{...props}` to the `<Fab>` component arguments and then spreading them into the component.

**Comment by rberger** [comment]
Setting the top level .rtf position to absolute did it for me. If I can figure it out, I will try to make a PR. Still pretty new to all this react stuff.. Thanks!

**Comment by tareqdayya** [comment]
Just add:
`transform: translate(0, 0) `
to the parent which you want to be the containing block.

**Comment by dericgw** [comment]
This will be fixed in v4 which I am about to release.
